import type { Metadata } from "next";
import Image from "next/image";
import { PageHero } from "@/components/PageHero";
import { Reveal } from "@/components/ui/Reveal";
import { team } from "@/data/team";
import { projects } from "@/data/projects";

export const metadata: Metadata = { title: "About", description: "Meet Atelier Arka—an interior architecture practice built around listening, material intelligence and enduring craft.", alternates:{canonical:"/about"} };
const journey=[["2016","The studio begins with one residential commission and a belief in slower, more attentive design."],["2019","Architecture and interior teams unite under one roof, creating a genuinely integrated practice."],["2022","Our bespoke furniture atelier opens, allowing every detail to be resolved in-house."],["2026","A multidisciplinary team now works across homes, hospitality and cultural spaces throughout India."]];

export default function AboutPage(){return <><PageHero eyebrow="The studio / About" title="We design from" italic="the inside out." intro="Not around a look, but around a life. Our work is grounded in observation, rigorous thinking and the pleasure of materials that age honestly."/>
  <section className="pb-24 md:pb-40"><div className="container-site grid gap-8 lg:grid-cols-12"><div className="image-cover aspect-[16/10] lg:col-span-8"><Image src={projects[0].cover} alt="Atelier Arka residential interior" fill sizes="70vw"/></div><div className="flex flex-col justify-end border-l border-[var(--line)] pl-7 lg:col-span-4"><span className="serif text-[clamp(6rem,13vw,13rem)] leading-none text-accent">10</span><p className="serif text-3xl">Years of considered practice</p><p className="mt-5 text-sm leading-7 text-muted">Our scale is deliberate: large enough to deliver complex work, intimate enough for principals to remain involved.</p></div></div></section>
  <section className="section-pad bg-[var(--paper-2)]"><div className="container-site"><p className="eyebrow text-accent">Our philosophy</p><div className="mt-10 grid gap-12 lg:grid-cols-2"><Reveal><h2 className="serif display-md">Quiet spaces.<br/>Strong ideas.<br/><i>Lasting value.</i></h2></Reveal><div className="grid gap-8 text-sm leading-7 text-muted md:grid-cols-2"><p>We believe luxury is less about display and more about resolution—the right proportion, a line that meets exactly, natural light arriving at the right hour.</p><p>Each project is singular because each client, site and way of living is singular. A shared visual language emerges through care, never formula.</p></div></div><div className="mt-20 grid border-l border-t border-[var(--line)] md:grid-cols-3">{[["01","Listen deeply","Before drawing, we learn the patterns and priorities that make a place yours."],["02","Edit rigorously","We pursue clarity through reduction, proportion and intentional material choices."],["03","Make beautifully","Design lives or dies in execution. We stay close to the work until completion."]].map(v=><div key={v[0]} className="border-b border-r border-[var(--line)] p-8"><span className="text-[9px] text-accent">{v[0]}</span><h3 className="serif mt-16 text-3xl">{v[1]}</h3><p className="mt-5 text-xs leading-6 text-muted">{v[2]}</p></div>)}</div></div></section>
  <section className="section-pad"><div className="container-site"><div className="grid gap-14 lg:grid-cols-12"><div className="lg:col-span-4"><p className="eyebrow text-accent">The journey</p><h2 className="serif display-md mt-7">A decade,<br/>still curious.</h2></div><div className="lg:col-span-8">{journey.map((j,i)=><div key={j[0]} className="grid grid-cols-[80px_1fr] gap-5 border-b border-[var(--line)] py-8 md:grid-cols-[130px_1fr]"><span className="serif text-3xl text-accent">{j[0]}</span><p className="max-w-xl text-sm leading-7 text-muted">{j[1]}</p></div>)}</div></div></div></section>
  <section className="bg-[#12120f] py-24 text-[#eee9df] md:py-36"><div className="container-site"><p className="eyebrow text-[#b79067]">The people behind the work</p><h2 className="serif display-md mt-6">A collective of<br/><i>different disciplines.</i></h2><div className="mt-16 grid gap-x-5 gap-y-16 md:grid-cols-2 lg:grid-cols-4">{team.map((m,i)=><article key={m.name} className={`${i%2?"lg:mt-20":""}`} data-cursor="OPEN"><div className="group image-cover aspect-[3/4]"><Image src={m.image} alt={m.name} fill sizes="(max-width:768px) 100vw, 25vw" className="grayscale transition-all duration-700 group-hover:grayscale-0"/><div className="absolute inset-x-0 bottom-0 translate-y-full bg-black/75 p-5 text-xs leading-5 text-white/70 backdrop-blur-md transition-transform duration-500 group-hover:translate-y-0">{m.bio}</div></div><h3 className="serif mt-5 text-3xl">{m.name}</h3><p className="mt-2 text-[9px] uppercase tracking-[.14em] text-white/45">{m.role}</p><div className="mt-4 flex justify-between border-t border-white/15 pt-3 text-[9px] text-white/45"><span>{m.experience}</span><span>{m.specialty}</span></div></article>)}</div></div></section>
  </>}
