"use client";
import Image from "next/image";
import Link from "next/link";
import { useRef, useState } from "react";
import { motion, useScroll, useTransform } from "framer-motion";
import { ArrowRight } from "lucide-react";
import { projects } from "@/data/projects";
import { services } from "@/data/services";
import { furniture } from "@/data/furniture";
import { testimonials } from "@/data/testimonials";
import { Reveal } from "@/components/ui/Reveal";
import { ArrowLink } from "@/components/ui/ArrowLink";
import { whatsappUrl } from "@/data/siteConfig";

export function Introduction() {
  const ref = useRef<HTMLDivElement>(null); const { scrollYProgress } = useScroll({ target:ref, offset:["start end","end start"] }); const y = useTransform(scrollYProgress,[0,1],[90,-80]);
  return <section id="introduction" className="section-pad architectural-grid relative overflow-hidden"><div className="container-site grid gap-14 lg:grid-cols-12 lg:items-center">
    <div className="lg:col-span-7"><p className="eyebrow text-accent">Studio ethos / 01</p><Reveal><h2 className="serif display-lg mt-8">Architecture,<br/>material and <i>emotion</i><br/>in quiet alignment.</h2></Reveal><Reveal delay={.1}><p className="mt-10 max-w-lg text-sm leading-7 text-muted">Atelier Arka is an interior architecture studio creating deeply personal spaces across India. We work from the inside out—beginning with rituals, movement and light, then resolving every surface, junction and object.</p></Reveal></div>
    <div className="relative lg:col-span-5"><motion.div style={{ y }} className="image-cover aspect-[3/4]"><Image src={projects[1].cover} alt="Contemporary villa with open architecture" fill sizes="(max-width:1024px) 100vw, 40vw" /></motion.div><div className="absolute -bottom-7 -left-7 h-28 w-28 border-b border-l border-[var(--accent)]"/><p className="absolute -right-4 top-6 origin-right rotate-90 text-[8px] uppercase tracking-[.2em] text-muted">Between light and matter</p></div>
  </div></section>;
}

export function FeaturedProjects() {
  return <section className="bg-[#12120f] py-24 text-[#eee9df] md:py-36"><div className="container-site"><div className="mb-12 flex items-end justify-between border-b border-white/15 pb-7"><div><p className="eyebrow text-[#b79067]">Selected work / 02</p><h2 className="serif mt-4 text-5xl md:text-7xl">Spaces of consequence.</h2></div><span className="hidden text-[10px] uppercase tracking-[.16em] text-white/45 md:block">Drag / Scroll →</span></div></div>
    <div className="no-scrollbar flex snap-x gap-5 overflow-x-auto px-[max(20px,calc((100vw-1440px)/2))] pb-8">
      {projects.slice(0,5).map((p,i)=><Link key={p.slug} href={`/portfolio/${p.slug}`} className="group relative min-w-[85vw] snap-center md:min-w-[62vw] lg:min-w-[48vw]" data-cursor="VIEW"><div className="image-cover aspect-[4/3]"><Image src={p.cover} alt={p.title} fill sizes="(max-width:768px) 85vw, 48vw" /></div><div className="mt-5 flex items-start justify-between"><div><p className="serif text-3xl md:text-4xl">{p.title}</p><p className="mt-2 text-[9px] uppercase tracking-[.16em] text-white/50">{p.location} · {p.category} · {p.year}</p></div><span className="grid h-11 w-11 place-items-center border border-white/25 transition-colors group-hover:bg-white group-hover:text-black"><ArrowRight size={16}/></span></div><span className="absolute left-4 top-4 text-[9px] tracking-[.2em] text-white/70">0{i+1}</span></Link>)}
    </div></section>;
}

export function Services() {
  const [active,setActive]=useState(0);
  return <section className="section-pad"><div className="container-site grid gap-14 lg:grid-cols-12"><div className="lg:col-span-4"><p className="eyebrow text-accent">Our practice / 03</p><h2 className="serif display-md mt-7">From first line<br/>to final object.</h2><div className="image-cover mt-12 hidden aspect-[4/5] lg:block"><Image src={projects[active%projects.length].cover} alt="Service visual" fill sizes="30vw" /></div></div><div className="lg:col-span-8">{services.map((s,i)=><button key={s.number} onMouseEnter={()=>setActive(i)} className="group grid w-full grid-cols-[42px_1fr_auto] items-center gap-3 border-b border-[var(--line)] py-5 text-left md:grid-cols-[70px_1fr_2fr_auto] md:py-7"><span className="text-[9px] text-accent">{s.number}</span><span className="serif text-2xl transition-transform duration-500 group-hover:translate-x-2 md:text-4xl">{s.title}</span><span className="hidden max-w-sm text-xs leading-5 text-muted opacity-0 transition-opacity duration-500 group-hover:opacity-100 md:block">{s.description}</span><ArrowRight size={16} className="transition-transform group-hover:translate-x-1"/></button>)}</div></div></section>;
}

const stats=[["10+","Years of practice"],["150+","Spaces completed"],["80+","Client stories"],["1.2M","Sq. ft. designed"]];
export function Numbers(){return <section className="bg-[var(--paper-2)] py-24 md:py-36"><div className="container-site"><p className="eyebrow text-accent">Measured in trust / 04</p><div className="mt-12 grid grid-cols-2 border-l border-t border-[var(--line)] lg:grid-cols-4">{stats.map((s,i)=><Reveal key={s[1]} delay={i*.08} className="border-b border-r border-[var(--line)] p-6 md:p-10"><strong className="serif block text-5xl font-normal md:text-7xl">{s[0]}</strong><span className="mt-4 block text-[9px] uppercase tracking-[.15em] text-muted">{s[1]}</span></Reveal>)}</div></div></section>}

const steps=["Discovery","Concept","Design","Material selection","Execution","Handover"];
export function Process(){const [active,setActive]=useState(0);return <section className="section-pad overflow-hidden"><div className="container-site"><p className="eyebrow text-accent">How we work / 05</p><div className="mt-10 grid gap-14 lg:grid-cols-2"><div className="relative aspect-[4/3] overflow-hidden lg:sticky lg:top-28 lg:h-[65vh]"><Image src={projects[(active+2)%projects.length].gallery[active%3]} alt="Design process" fill className="object-cover" sizes="50vw"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/75 to-transparent p-8 pt-28 text-white"><span className="serif text-8xl italic text-white/30">0{active+1}</span><p className="serif text-4xl">{steps[active]}</p></div></div><div>{steps.map((s,i)=><button onMouseEnter={()=>setActive(i)} onClick={()=>setActive(i)} key={s} className={`group flex w-full items-center gap-7 border-b border-[var(--line)] py-8 text-left transition-opacity ${active===i?"opacity-100":"opacity-35 hover:opacity-75"}`}><span className="text-[9px] text-accent">0{i+1}</span><span className="serif text-4xl md:text-6xl">{s}</span></button>)}<p className="mt-10 max-w-lg text-sm leading-7 text-muted">A transparent, disciplined journey from understanding your world to placing the very last object. One team remains accountable throughout.</p></div></div></div></section>}

export function FurniturePreview(){return <section className="bg-[#d9d0c2] py-24 text-[#191814] md:py-36"><div className="container-site flex items-end justify-between"><div><p className="eyebrow text-[#76502f]">The object collection / 06</p><h2 className="serif display-md mt-6">Furniture, resolved<br/><i>as architecture.</i></h2></div><ArrowLink href="/furniture">Explore collection</ArrowLink></div><div className="no-scrollbar mt-16 flex gap-5 overflow-x-auto pb-6">{furniture.slice(0,5).map((f,i)=><Link href="/furniture" data-cursor="EXPLORE" key={f.slug} className={`group min-w-[72vw] md:min-w-[36vw] ${i%2?"md:pt-20":""}`}><div className="image-cover aspect-[4/5]"><Image src={f.image} alt={f.name} fill sizes="(max-width:768px) 72vw, 36vw"/></div><div className="mt-4 flex justify-between border-t border-black/20 pt-4"><span className="serif text-2xl">{f.name}</span><span className="eyebrow">0{i+1}</span></div></Link>)}</div></section>}

export function Testimonials(){const [i,setI]=useState(0);const t=testimonials[i];return <section className="section-pad"><div className="container-site max-w-6xl text-center"><p className="serif text-8xl leading-none text-accent">“</p><motion.blockquote key={i} initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="serif mx-auto max-w-5xl text-[clamp(2.2rem,5vw,5rem)] leading-[1.05]">{t.quote}</motion.blockquote><p className="mt-10 text-[9px] uppercase tracking-[.18em] text-muted">{t.name} · {t.project} · {t.location}</p><div className="mt-8 flex justify-center gap-2">{testimonials.map((_,x)=><button key={x} onClick={()=>setI(x)} aria-label={`Show testimonial ${x+1}`} className={`h-px transition-all ${x===i?"w-14 bg-[var(--accent)]":"w-7 bg-[var(--line)]"}`}/>)}</div></div></section>}

export function FinalCTA(){return <section className="grain relative flex min-h-[85vh] items-end overflow-hidden text-white"><Image src={projects[4].cover} alt="Luxury hospitality interior" fill className="object-cover" sizes="100vw"/><div className="absolute inset-0 bg-black/55"/><div className="container-site relative z-10 pb-16 md:pb-24"><p className="eyebrow text-white/60">Your space, considered</p><h2 className="serif mt-6 max-w-5xl text-[clamp(3.8rem,8vw,8.5rem)] leading-[.86] tracking-[-.05em]">Let’s make something<br/><i>worth remembering.</i></h2><div className="mt-10 flex flex-wrap gap-3"><ArrowLink href="/contact" light>Start your project</ArrowLink><ArrowLink href={whatsappUrl()} light>WhatsApp us</ArrowLink></div></div></section>}
