import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { projects } from "@/data/projects";
import { ArrowLink } from "@/components/ui/ArrowLink";

export function generateStaticParams(){return projects.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=projects.find(x=>x.slug===slug);return p?{title:p.title,description:p.description,alternates:{canonical:`/portfolio/${p.slug}`},openGraph:{images:[p.cover]}}:{title:"Project"}}
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(x=>x.slug===slug);if(!p)notFound();const current=projects.findIndex(x=>x.slug===slug);const next=projects[(current+1)%projects.length];const schema={"@context":"https://schema.org","@type":"CreativeWork",name:p.title,description:p.description,image:p.gallery};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section id="top" className="relative min-h-[100svh] text-white"><Image src={p.cover} alt={p.title} fill priority className="object-cover" sizes="100vw"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/10 to-black/30"/><div className="container-site relative z-10 flex min-h-[100svh] flex-col justify-end pb-12 pt-36"><p className="eyebrow text-white/65">{p.category} / {p.location}</p><h1 className="serif display-xl mt-6">{p.title}</h1><div className="mt-10 grid gap-5 border-t border-white/25 pt-6 text-[9px] uppercase tracking-[.15em] text-white/70 grid-cols-2 md:grid-cols-4"><span>Location<br/><b className="mt-2 block text-white">{p.location}</b></span><span>Year<br/><b className="mt-2 block text-white">{p.year}</b></span><span>Area<br/><b className="mt-2 block text-white">{p.area}</b></span><span>Discipline<br/><b className="mt-2 block text-white">{p.category}</b></span></div></div></section>
  <section className="section-pad"><div className="container-site grid gap-14 lg:grid-cols-12"><div className="lg:col-span-4"><p className="eyebrow text-accent">The brief</p></div><div className="lg:col-span-8"><p className="serif text-[clamp(2.4rem,5vw,5.5rem)] leading-[1.02]">{p.description}</p><div className="mt-14 grid gap-10 md:grid-cols-2"><div><p className="eyebrow mb-4 text-accent">Design philosophy</p><p className="text-sm leading-7 text-muted">{p.philosophy}</p></div><div><p className="eyebrow mb-4 text-accent">Material palette</p><p className="text-sm leading-7 text-muted">{p.materials.join(" · ")}</p></div></div></div></div></section>
  <section>{p.gallery.map((img,i)=><div key={img} className={`relative ${i===1?"mx-auto my-8 aspect-[4/3] w-[80%] md:my-24 md:w-[65%]":"aspect-[16/10] w-full"}`}><Image src={img} alt={`${p.title} — view ${i+1}`} fill sizes={i===1?"70vw":"100vw"} className="object-cover"/></div>)}</section>
  <section className="section-pad"><div className="container-site grid gap-10 border-y border-[var(--line)] py-16 md:grid-cols-2"><div><p className="eyebrow text-accent">The challenge</p><p className="serif mt-5 text-3xl leading-tight md:text-4xl">{p.challenge}</p></div><div><p className="eyebrow text-accent">Our response</p><p className="serif mt-5 text-3xl leading-tight md:text-4xl">{p.solution}</p></div></div></section>
  <section className="relative min-h-[75vh] text-white"><Image src={next.cover} alt={next.title} fill className="object-cover" sizes="100vw"/><div className="absolute inset-0 bg-black/55"/><div className="container-site relative z-10 flex min-h-[75vh] flex-col items-start justify-end pb-16"><p className="eyebrow text-white/60">Next project</p><h2 className="serif display-lg mt-5">{next.title}</h2><div className="mt-8"><ArrowLink href={`/portfolio/${next.slug}`} light>View project</ArrowLink></div></div></section></>}
